Better error messages on boot WIP
Unplugged my external and I had to go through the bugdump again - no error
in the GUI. Took the opportunity to redo some part of the error handling
in bash.py.
The printing of random errors in bash needs revisiting.

Wrye Bash Launcher.pyw:

- Changed the loader to throw ImportError on failure  - see
https://www.python.org/dev/peps/pep-0302/:

  >A loader object also has one method:

  >loader.load_module(fullname)

  >This method returns the loaded module or raises an exception,
  > preferably ImportError if an existing exception is not being propagated

WIP - scrutinize PEP compliance

- Tried to keep the traceback of the original exception - idea from:
http://stackoverflow.com/questions/1350671/inner-exception-with-traceback-in-python

The comment on nested import errors refers to things like:

fail bash\basher\constants.py
fail bash\basher.py
Traceback (most recent call last):
  File "bash\bash.py", line 496, in _showErrorInGui
    import basher
  File "Wrye Bash Launcher.pyw", line 76, in load_module
    exec compile(code, initfile, 'exec') in mod.__dict__
  File "bash\basher\__init__.py", line 93, in <module>
    from .constants import colorInfo, settingDefaults, karmacons, installercons, \
  File "Wrye Bash Launcher.pyw", line 63, in load_module
    mod = imp.load_source(fullname,filename+ext,fp)
  File "bash\basher\constants.py", line 576, in <module>
    ((bosh.tooldirs['OblivionBookCreatorPath'],
ImportError: caused by ImportError(u"caused by KeyError('OblivionBookCreatorPath',)",)

See also (exception handling tips):

http://www.ianbicking.org/blog/2007/09/re-raising-exceptions.html